---
- name: Install Nginx
  apt: pkg=nginx state=installed update_cache=true
  notify:
  - Start Nginx
  register: nginxinstalled

- name: Create Web Root
  when: nginxinstalled|success
  file: dest=/www/louisville.io/htdocs mode=2775 state=directory owner=www-data group=www-data
  notify:
  - Reload Nginx

- name: Add louisville.io nginx vhost config
  when: nginxinstalled|success
  register: nginxconfig
  copy: src=louisville.io.conf dest=/etc/nginx/sites-available/louisville.io.conf owner=root group=root

- name: Activate the louisville.io nginx site
  when: nginxinstalled|success
  file: src=/etc/nginx/sites-available/louisville.io.conf dest=/etc/nginx/sites-enabled/louisville.io.conf state=link
  notify:
    - Reload Nginx

- name: Disable Default Site
  when: nginxinstalled|success
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: Web Root Permissions
  when: nginxinstalled|success
  file: dest=/www/louisville.io mode=775 state=directory owner=www-data group=www-data recurse=yes
  notify:
    - Reload Nginx

- name: Add slackin.louisville.io nginx vhost config
  when: nginxinstalled|success
  register: nginxconfig
  copy: src=slackin.louisville.io.conf dest=/etc/nginx/sites-available/slackin.louisville.io.conf owner=root group=root

- name: Activate the slackin.louisville.io nginx site
  when: nginxinstalled|success
  file: src=/etc/nginx/sites-available/slackin.louisville.io.conf dest=/etc/nginx/sites-enabled/slackin.louisville.io.conf state=link
  notify:
    - Reload Nginx
