---
- name: Add Certbot PPA
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: Install Certbot
  apt: pkg=python-certbot-nginx state=installed update_cache=true

- name: Install Nginx
  apt: pkg=nginx state=installed update_cache=true
  notify:
  - Start Nginx
  register: nginxinstalled

- name: Create Web Root
  when: nginxinstalled|success
  file: dest=/www/louisvilletech.org/htdocs mode=2775 state=directory owner=www-data group=www-data
  notify:
  - Reload Nginx

- name: Add louisvilletech.org nginx vhost config
  when: nginxinstalled|success
  register: nginxconfig
  copy: src=louisvilletech.org.conf dest=/etc/nginx/sites-available/louisvilletech.org.conf owner=root group=root

- name: Activate the louisvilletech.org nginx site
  when: nginxinstalled|success
  file: src=/etc/nginx/sites-available/louisvilletech.org.conf dest=/etc/nginx/sites-enabled/louisvilletech.org.conf state=link
  notify:
    - Reload Nginx

- name: Disable Default Site
  when: nginxinstalled|success
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: Web Root Permissions
  when: nginxinstalled|success
  file: dest=/www/louisvilletech.org mode=775 state=directory owner=www-data group=www-data recurse=yes
  notify:
    - Reload Nginx

- name: Add slackin.louisvilletech.org nginx vhost config
  when: nginxinstalled|success
  register: nginxconfig
  copy: src=slackin.louisvilletech.org.conf dest=/etc/nginx/sites-available/slackin.louisvilletech.org.conf owner=root group=root

- name: Activate the slackin.louisvilletech.org nginx site
  when: nginxinstalled|success
  file: src=/etc/nginx/sites-available/slackin.louisvilletech.org.conf dest=/etc/nginx/sites-enabled/slackin.louisvilletech.org.conf state=link
  notify:
    - Reload Nginx

- name: Get louisvilletech.org certificates
  command: certbot -n --nginx --agree-tos --email eric@ericlathrop.com --redirect --uir --hsts --staple-ocsp --must-staple -d louisvilletech.org -d www.louisvilletech.org -d slackin.louisvilletech.org
  notify:
    - Reload Nginx
