- name: Download site
  git: repo=https://github.com/louisvilletech/louisvilletech.org.git dest=/home/deploy/louisvilletech.org

- name: Install dependencies
  npm: path=/home/deploy/louisvilletech.org production=yes

- name: Install build script
  template: src=generate-site.sh
            dest=/home/deploy/louisvilletech.org/generate-site.sh
            mode=775

- name: Build site
  command: ./generate-site.sh chdir=/home/deploy/louisvilletech.org

- name: Copy site
  command: rsync --recursive --copy-links --delete /home/deploy/louisvilletech.org/dest/ /www/louisvilletech.org/htdocs

- name: Install crontab job
  cron: name="Generate louisvilletech.org"
        minute="*/10"
        user="deploy"
        job="cd /home/deploy/louisvilletech.org && ./generate-site.sh && rsync --recursive --copy-links --delete /home/deploy/louisvilletech.org/dest/ /www/louisvilletech.org/htdocs"
